<?xml version="1.0"?>
<package format="3">
  <name>mpc</name>
  <version>0.0.1</version>
  <description>Model Predictive Controller</description>
  <maintainer email="yixuany@mit.edu">Lucas</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>message_filters</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
